DROP TABLE `analytics_events`;--> statement-breakpoint
DROP TABLE `audio_generations`;--> statement-breakpoint
DROP TABLE `audio_stems`;--> statement-breakpoint
DROP TABLE `billing_logs`;--> statement-breakpoint
DROP TABLE `blog_posts`;--> statement-breakpoint
DROP TABLE `book_purchases`;--> statement-breakpoint
DROP TABLE `books`;--> statement-breakpoint
DROP TABLE `brazilian_celebrations`;--> statement-breakpoint
DROP TABLE `choir_compositions`;--> statement-breakpoint
DROP TABLE `choir_parts`;--> statement-breakpoint
DROP TABLE `churches`;--> statement-breakpoint
DROP TABLE `community_comments`;--> statement-breakpoint
DROP TABLE `community_hub`;--> statement-breakpoint
DROP TABLE `community_posts`;--> statement-breakpoint
DROP TABLE `community_rankings`;--> statement-breakpoint
DROP TABLE `contact_submissions`;--> statement-breakpoint
DROP TABLE `conversion_funnel_steps`;--> statement-breakpoint
DROP TABLE `course_enrollments`;--> statement-breakpoint
DROP TABLE `courses`;--> statement-breakpoint
DROP TABLE `credit_transactions`;--> statement-breakpoint
DROP TABLE `custom_repertoire`;--> statement-breakpoint
DROP TABLE `custom_songs`;--> statement-breakpoint
DROP TABLE `digital_books`;--> statement-breakpoint
DROP TABLE `educational_videos`;--> statement-breakpoint
DROP TABLE `event_blocks`;--> statement-breakpoint
DROP TABLE `event_templates`;--> statement-breakpoint
DROP TABLE `events`;--> statement-breakpoint
DROP TABLE `favorite_transpositions`;--> statement-breakpoint
DROP TABLE `favorites`;--> statement-breakpoint
DROP TABLE `instrument_listings`;--> statement-breakpoint
DROP TABLE `marketplace_listings`;--> statement-breakpoint
DROP TABLE `marketplace_messages`;--> statement-breakpoint
DROP TABLE `ministry_members`;--> statement-breakpoint
DROP TABLE `music_ministries`;--> statement-breakpoint
DROP TABLE `newsletter_subscriptions`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `patron_saints`;--> statement-breakpoint
DROP TABLE `priest_profiles`;--> statement-breakpoint
DROP TABLE `priest_stories`;--> statement-breakpoint
DROP TABLE `retreat_songs`;--> statement-breakpoint
DROP TABLE `retreats`;--> statement-breakpoint
DROP TABLE `seller_ratings`;--> statement-breakpoint
DROP TABLE `song_contributions`;--> statement-breakpoint
DROP TABLE `song_feedback`;--> statement-breakpoint
DROP TABLE `song_usage_stats`;--> statement-breakpoint
DROP TABLE `songs`;--> statement-breakpoint
DROP TABLE `story_comments`;--> statement-breakpoint
DROP TABLE `subscriptions`;--> statement-breakpoint
DROP TABLE `testimonials`;--> statement-breakpoint
DROP TABLE `user_profile_community`;--> statement-breakpoint
DROP TABLE `video_comments`;--> statement-breakpoint
DROP TABLE `video_ratings`;--> statement-breakpoint
DROP TABLE `voice_compatibility`;--> statement-breakpoint
DROP TABLE `word_of_the_day`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `churchId`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `voicePart`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `stripeCustomerId`;